### ISSUE TITLE
Min Browser arguments!

### ISSUE THREAD

**Issue by AdrianoAz** [w-e-w/sd-webui-custom-autolaunch#1]
Hi, I don't know if it's the right channel, but I decided to try anyway, it's not a bug, but I can't put the arguments correctly for the min browser, which is the lightest browser that runs A1111 that I found, it seems that the argument its original is min <url>, but neither with the example nor mixing I can do it. It would be very worth it, thank you.

**Comment by w-e-w** [comment]
seem to work fine for me

```shell
"C:\Users\<user>\AppData\Local\min\min.exe" {url}
```
> note this is on windows

**Comment by w-e-w** [comment]
you should be able to test out the command in CMD or whatever terminal of the platform you are on
> lol I don't even know what OS you're using
